### ISSUE TITLE
Not able to do npm install

### ISSUE THREAD

**Issue by osi-bhushankumar** [NuCivic/react-dashboard#7]
CC: @alexrollin 
HI,

Facing error while doing npm install after cloning it.

**Comment by topicus** [comment]
Hi @osi-bhushankumar, thanks for reporting this.  What's the error are you getting? Did you have the peerDependencies (react and react-dom) already installed?

**Comment by osi-bhushankumar** [comment]
This is http://prnt.sc/au6mvx. While we are trying to install dependencies.

**Comment by topicus** [comment]
It was a bug. Try again.

Thanks!

**Comment by osi-bhushankumar** [comment]
Now, It's stuck here : 

' deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt''

**Comment by topicus** [comment]
@osi-bhushankumar I think that's a warning. Shouldn't block you to install the library. However I think it will be easy for you to work with the boilerplate https://github.com/NuCivic/react-dashboard-boilerplate

**Comment by osi-bhushankumar** [comment]
Thank you
